Repository HackYourFutureBelgium/template-html-css, pull requests merged in 2023-04, with the labels that each got.

#2 Update lint-and-validate.yml
  .github/workflows/lint-and-validate.yml
Labels: bug

#3 Update repo setup instructions
  README.md
Labels: enhancement

#4 Merge changes from DeNepo
  .cspell.json
  .github/ISSUE_TEMPLATE/issue.md
  .github/pull_request_template.md
  .gitignore
  .vscode/settings.json
Labels: documentation, enhancement
